### ISSUE TITLE
currentVersion not working

### ISSUE THREAD

**Issue by fritzrichter** [allegro/axion-release-plugin#103]
G'day together. I have problems with the plugin showing the right version via "currentVersion". Let me start with the shell output:

```
fritz@local:user-service>git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
fritz@local:user-service>git tag
fritz@local:user-service>./gradlew currentVersion
[buildinfo] Not using buildInfo properties file for this build.
:currentVersion

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL

Total time: 4.263 secs
fritz@local:user-service>./gradlew release
[buildinfo] Not using buildInfo properties file for this build.
:verifyRelease
Looking for uncommitted changes..
Checking if branch is ahead of remote..
:release
Creating tag: user-service-0.1.0
Pushing all to remote: origin

BUILD SUCCESSFUL

Total time: 8.312 secs
fritz@local:user-service>git tag
user-service-0.1.0
fritz@local:user-service>./gradlew currentVersion
[buildinfo] Not using buildInfo properties file for this build.
:currentVersion

Project version: 0.1.0-SNAPSHOT

BUILD SUCCESSFUL

Total time: 4.441 secs
fritz@local:user-service>
```

My Gradle config
```
project.version = scmVersion.version
scmVersion {
    tag {
        prefix = 'user-service'
    }
    repository {
        scmVersion.repository.customUsername = "${git_user}"
        scmVersion.repository.customPassword = "${git_password}"
    }
    versionCreator 'versionWithBranch'
}
```
The tagging and releasing somehow works fine, but if I invoke the currentVersion again, it's just not increasing and showing the right new number. 

Any idea?

**Comment by adamdubiel** [comment]
Ah, there is a problem with configuration ordering: `project.version=...` needs to come after `scmVersion { }` configuration, otherwise version is read using default. It's actually stated in docs as well :) http://axion-release-plugin.readthedocs.org/en/latest/configuration/basic_usage.html#basic-configuration

**Comment by fritzrichter** [comment]
thanks :) i did not read that...

**Comment by adamdubiel** [comment]
No problem :)

**Comment by dbacinski** [comment]
"Order of definition does matter! First, you need to apply the plugin, then configure it using scmVersion extension and only then current version can be set for whole project via scmVersion.version." 

This should be bolded on every page. Just wasted a lot of time to figure out why currentVersion is not working and the problem was with script ordering:)
