### ISSUE TITLE
Provide single flag instead of nextVersion and forceVersion

### ISSUE THREAD

**Issue by jkubrynski** [allegro/axion-release-plugin#104]
Currently there are two parameters for specifying version.
```
./gradlew markNextVersion -Prelease.nextVersion=2.0.0
./gradlew release -Prelease.forceVersion=3.0.0
```

Assuming these are two different tasks it'll be more consist to have only one parameter (for example ```-Prelease.version```)

**Comment by adamdubiel** [comment]
Fixed in `1.3.3`, took some time, hope it was worth it ;)

**Comment by jkubrynski** [comment]
:+1:

**Comment by vbuell** [comment]
Wait. What if user wants to do both these tasks in one gradle exec?

**Comment by adamdubiel** [comment]
Okay, so `relese.forceVersion` and `release.nextVersion` are still there. However i never tried running both of these tasks together and that was not considered when designing them, so as far as i'm concerned the behavior is unknown. It would also depend a lot on how Gradle runs these tasks (order matters), since they have no explicit before/after relationship defined.
