### ISSUE TITLE
Problem Pushing to Remote

### ISSUE THREAD

**Issue by shashdr** [allegro/axion-release-plugin#134]
Jenkins release build is throwing this error on performing release task. I have SSH keys and credentials on Jenkins and expect axion release to pick it from Jenkins workspace and push the tag to remote. But it failed and threw error. Here's my git config in Jenkins
![screen shot 2016-04-21 at 9 37 51 pm](https://cloud.githubusercontent.com/assets/976823/14730227/2edd8d30-080a-11e6-9399-47266e0a4a98.png)
. I tried setting custom key property on build.gradle and pulled externally the SSH key from file, and that worked. Can the axion release work with Jenkins without authorization issues?

**Comment by adamdubiel** [comment]
I would say there is no issue here :) `axion-release` is not a Jenkins (nor Bamboo nor TeamCity nor ...) plugin, it is a Gradle plugin. Being CI tool agnostic, it exposes a lot of options that allow on easy integration with them. I do not intend to write any CI-specific code (especially that i have never used Jenkins), you should just configure `axion-release` to work in your environment.

**Comment by shashdr** [comment]
I tried from terminal ./gradlew release and it works absolutely fine. I checked whether I have configured the handshake between jenkins and github properly by using researchgate gradle release plugin, it works fine as well. Am I missing something with axion-release config from Jenkins or is it a common issue ( Problem pushing to remote) encountered earlier.

**Comment by adamdubiel** [comment]
Locally it works fine, because you probably have some ssh keys configuration which gives you write permissions to the repository you want to release. However on Jenkins you probably need to configure axion-release to i.e. read some SSH key or use username & password. 

I don't know what the exact problem is, but maybe these pieces of docs will help you?

http://axion-release-plugin.readthedocs.org/en/latest/configuration/ci_servers.html#jenkins
http://axion-release-plugin.readthedocs.org/en/latest/configuration/authorization.html#ssh-key-password
