### ISSUE TITLE
Like Maven release plugin behaviour

### ISSUE THREAD

**Issue by Evgen1000end** [allegro/axion-release-plugin#144]
Oh, sorry) i pressed button accidentally.

With a little help of Maven release plugin i can provide the following behavior: 
1) Take current SNAPSHOT version (from POM.xml)
2) Cut "-SNAPSHOT" (plugin modifies pom.xml)
3) Tag, commit etc
4) Generate new version (plugin modifies pom.xml) 
5) Commit

This plugin can do this great, but one stores version implicit and don't modify build.gradle. Is it possible to provide a explicit version in the script file?

**Comment by adamdubiel** [comment]
Some more details would be great :)

**Comment by agusmba** [comment]
I'm not an expert at all on this plugin (just a happy user), so please treat my opinion with a grain of salt.

I think one of the main points of this plugin is precisely the lack of dependency on any hardcoded versioning on a file. At least this is the reason why I chose to use it.
 
Depending on your specific needs you could use axion-release-plugin (which I love) with some extra task code to read/retrieve the version from a properties file.

I have looked at several other gradle plugins for automatic version management, but since it is quite the opposite from what it seems you're looking for, I cannot recommend any specific one. Maybe go through [the plugin portal](https://plugins.gradle.org/search?term=version) to see if one fits your needs.

**Comment by adamdubiel** [comment]
+1 on @agusmba comment. The core idea behind the plugin is to leave hardcoded versions behind and use Version Control System for what it was created - versioning :) In this case, we want Git to be the single source of truth about version.

PS. Thanks for the kind words @agusmba !
