### ISSUE TITLE
Cannot use version incrementing with markNextVersion Task

### ISSUE THREAD

**Issue by nicholashauschild** [allegro/axion-release-plugin#153]
I would like to be able to automatically increment the major version via command line, when having a versionIncrementer set to 'incrementMinor' in build.gradle.

I have tried a couple things to see if it was available already, but neither worked:
- Trying with markNextVersion, and using the `release.versionIncrementer` flag.  This failed to run.

```
$ ./gradlew markNextVersion -Prelease.versionIncrementer=incrementMajor
:markNextVersion FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':markNextVersion'.
> No next version specified! Use -Prelease.version to set next version.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
- Trying with release, and the `release.versionIncrementer` flag.  This ran successfully, but didn't produce the desired result.  I was hoping to have a release of 0.4.0, and the next version be set to 1.0.0 (which would produce 1.0.0-SNAPSHOT on commits that weren't tagged as the release)

```
$ ./gradlew cV
:currentVersion

Project version: 0.4.0-SNAPSHOT

BUILD SUCCESSFUL

Total time: 7.625 secs

$ ./gradlew release -Prelease.versionIncrementer=incrementMajor
:verifyRelease
Looking for uncommitted changes..
Checking if branch is ahead of remote..
Skipping snapshot dependencies check
:release
Creating tag: release-1.0.0
Pushing all to remote: origin

BUILD SUCCESSFUL
```

Any thoughts on how I might accomplish this?

**Comment by adamdubiel** [comment]
`release` and `markNextVersion` have very different goals. Release makes a current release, so specifying incrementer changes how *released* version is bumped, thus you observe `0.4.0` -> `1.0.0`.

`markNextVersion` on the other hand does not use incrementers at all. It requires you to specify what should be the next version, because this is usually a manual step (i.e. a human has to decide that we will be now working on `1.0.0` and not `0.4.1`).

So the shortest answer to your problem would be to run:

```
./gradlew makrNextVersion -Prelease.version=1.0.0
``` 

This requires you to specify version though. I assume that you would rather not do it by hand? If so - why?

**Comment by nicholashauschild** [comment]
I agree that there is a manual aspect to this, but I would like to have the process be something like:
- Run major/patch version increment build

rather than something more akin to:
- Look up the previous version
- Determine the next value (the truly difficult part :smile:)
- Type the determined value (and don't fat finger it)
- Run build/execute command/whatever...

I would think a typical workflow would be to only increment the major/patch version anyways.  So while the decision itself is manually done by a human, the act of determining and updating the version doesn't always need to be.

**Comment by adamdubiel** [comment]
Does this *"Run major/patch version increment build"* mean releasing new version? Or just marking that from now on snapshots will be `1.0.0`? This is the part i don't fully understand.

In `axion-release` language, do you want (or):

* `./gradlew release`
* `./gradlew markNextVersion`
* `./gradlew release && ./gradlew markNextVersion`

**Comment by nicholashauschild** [comment]
No, the _Run major/patch version increment build_ wouldn't be a release of a new version, but a means to specify that new commits will be SNAPSHOTS of the incremented major/patch.

`markNextVersion` is where I would like to see this functionality.  I only mentioned the others as I was testing to see if such a feature was already available.

**Comment by adamdubiel** [comment]
Okay, so it took me some time and messages, but now i understand that you would want `markNextVersion` to simply use automatic version increments instead of providing it manually.

It seems obvious now, but i had to ask more questions to be sure :) Short answer is: it's not possible at the moment, but i imagine sth like `./gradlew markNextVersion -Prelease.autoIncrement` could switch version marker into auto mode, making use of incrementers. Doable, but due to my constant lack of time - i can't give you any timeline :)

I could however find time to guide you through code changes, review & release them if you are interested.

**Comment by nicholashauschild** [comment]
Sure thing.  I was somewhat expecting that I might be doing the work myself.  I primarily was wondering if the functionality already existed, and I was just unable to find it.

I will be reaching out to my company's Open Source team to fork this repo, to give me a space to work in.

Thanks!

**Comment by adamdubiel** [comment]
Okay, looking forward to PR or questions :) Use gitter channel i just created if you want to discuss something: https://gitter.im/allegro/axion-release-plugin

**Comment by rbrindl** [comment]
It looks like this problem has been resolved, everything works as expected.
