### ISSUE TITLE
Treat project as new snapshot version when repo contains changed files

### ISSUE THREAD

**Issue by adamdubiel** [allegro/axion-release-plugin#17]
As a user, i want axion-release to treat repository with changed (but uncommited) files as next SNAPSHOT version. This should not take effect, when checks are disabled.

**Comment by vbuell** [comment]
I'd say we should have even three levels of stability:

1. Treat as snapshot if not on tag (current behavior)
2. Treat as snapshot if not on tag or on tag with changed files (this issue)
3. Treat as snapshot if not on tag or on tag but the tag was created before this run. In other words, treat stable only for the build that is releasing now

The third case is mainly for CI jobs to avoid situations when new builds run of already released master branch are being treated as stable and trying to republish its artifacts. In general, the definition of stability of the project may be defined as an imaginary point on the timeline when the release was made (successfully); every consequent builds may or not be stable due to any side effects (dependencies, health of subsystems, etc) even if the codebase is intact.

**Comment by adamdubiel** [comment]
I think the 3rd behavior should be managed using flag - we add/modify some files that are not part of repository during our CI build and i wouldn't want them to corrupt my version.

**Comment by vbuell** [comment]
Agreed

**Comment by vbuell** [comment]
Oh. I just realized that 3rd one probably is hardy doable due to the fact that a plugin does not allow to release and publish at the same run...

**Comment by adamdubiel** [comment]
I found some time to fix this issue, it's in develop now. By default uncommitted changes are ignored and have no effect (backwards compatibility), but its easy to change:

```
scmVersion {
    ignoreUncommittedChanges = false
}
```

It can be always enabled by using flag:

```
./gradlew cV -Prelease.ignoreUncommittedChanges
```

Of course it's all in the docs as well.
