### ISSUE TITLE
Another project for you to investigate and coordinate with

### ISSUE THREAD

**Issue by mikezx6r** [allegro/axion-release-plugin#180]
This is not a defect, but I don't know how to reach you other than this.

First, amazing plugin! Wanted to bring to your attention a similar plugin.

I've been using https://github.com/ajoberstar/gradle-git for managing my versions. He developed it for the same reasons you did, and either you both started at the same time, or you just didn't find each other.

Many of the same principles and problems solved, just in slightly different ways. I've only just started reading your docs, but it appears your config is much easier to understand. I find gradle-git is difficult to understand when it comes to heavier customization.

Gradle-git does a nicer job with the actual version. No need to define project.version. Something for you to investigate, and thought you'd like to see another plugin very similar to yours.

I'm going to review your docs, and do some POC's. This may become my version plugin going forwards.

Again, thank you for the efforts.

**Comment by agusmba** [comment]
@mikezx6r I followed the same route you have about a year ago.
See https://thewaysoftech.wordpress.com/2016/05/25/managing-your-project-version-with-gradle-plugins/ for a story which will sound familiar to you.
 
Both are great plugins, but I feel @adamdubiel 's one fits better with what I'd like a version plugin to do.

Enjoy!

**Comment by adamdubiel** [comment]
HI,

First of all thanks for all the kind words :) It's nice to see that the work i'm doing helps other people, not just my company.

Digging into the history of axion-release, i remember doing quite a bit of research before starting to write this plugin (i even listed some plugins in README, i should probably update it) and at the time none of it was simple/easy enough. Mind, that i was not just writing a plugin for myself, but it was to be used by 50+ teams in 300+ projects at my company. So what i was really looking for was:

* minimal configuration
* easy to configure and extend, as i knew there were a lot of teams with weird  practices that i needed to cover so that they would not stray to using some other release solution

After some deliberation we just started coding this plugin. I think at that point in time `gradle-git` was much less developed and polished, with a bit of different philosophy (like importing GrGit in `build.gradle`) than it is now.

@mikezx6r thanks for suggestion about `project.version`, i will take a look at it.

@agusmba thanks for the article link :)
