### ISSUE TITLE
-Prelease.forceVersion switch makes current stable version a SNAPSHOT version

### ISSUE THREAD

**Issue by vbuell** [allegro/axion-release-plugin#208]
Just noticed that `-Prelease.forceVersion` switch specified on some gradle tasks like `publish` or `currentVersion` makes stable version a SNAPSHOT version as if current git position would be not on tag.

**STR:**

```console
> git tag -l
app-1.1.1
app-1.1.2

> git log --decorate=full -n1
commit XXXXXXXXXX (HEAD -> refs/heads/release/1.1, tag: refs/tags/app-1.1.2)
...cut off...

> gradle cV
Project version: 1.1.2

BUILD SUCCESFUL

> gradle cV -Prelease.forceVersion=1.1.2
Project version: 1.1.2-SNAPSHOT

BUILD SUCCESFUL
```

build.gradle:
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'pl.allegro.tech.build', name: 'axion-release-plugin', version: '1.8.1'
    }
}

apply plugin: 'pl.allegro.tech.build.axion-release'

scmVersion {
    tag.prefix = 'app'
}

allprojects {
    project.version = scmVersion.version
}
```

**Comment by vbuell** [comment]
reproduceable on axion plugin versions: 1.6.0 and 1.8.1

will put minimized gradle build configuration soon

**Comment by vbuell** [comment]
minimized build.gradle added

**Comment by adamdubiel** [comment]
Thanks for the report, but i don't think it's a bug. snapshot-if-force is explicitly coded in evaluation of `isSnapshot` flag [here](https://github.com/allegro/axion-release-plugin/blob/9d68d53202695fdf8e4817c2dd61a6f522908c2a/src/main/groovy/pl/allegro/tech/build/axion/release/domain/VersionFactory.groovy#L53). However it is not covered by any explicit test.

I think that the reason behind it is that forcing version change on an already tagged commit introduces a change (version change) and so you should have the possibility to release it.

If no snapshot was added, you would not be able to release same tag with different versions (i know it might be useful to some).

On the other hand if force version didn't add snapshot, you could publish release artifact with version that could not be traced back to any commit.

However in your examples it does look weird, because you force the same version as the current one. I guess this is the real problem?

**Comment by vbuell** [comment]
That's the pattern we follow: when releasing to a specific version we would like to force version for both commands: release and publish. The reason behind this is that we faced a number of different issues in the past related to our workflow, bamboo integration, etc. So we just want to be 100% sure that the version of released artifact in nexus will be the same as we asked for.

**Comment by adamdubiel** [comment]
Will this: #209  be enough?

**Comment by vbuell** [comment]
Yeah, that'll solve the issue. Thanks
