### ISSUE TITLE
Current version resolution is not respecting version incremented

### ISSUE THREAD

**Issue by piotrchowaniec** [allegro/axion-release-plugin#247]
I'm not sure if this is a bug, so please close in case it doesn't.
When I have version incrementer set to increment minor part of the version then calling `./gradlew currentVersion` gives different result than version created using `./gradlew release`.
I've created a test for this case, so you can check the issue.
Please take a look at my [fork](https://github.com/piotrchowaniec/axion-release-plugin/blob/respectVersionIncrementer/src/test/groovy/pl/allegro/tech/build/axion/release/domain/VersionResolverTest.groovy) at test `VersionResolverTest#current version should respect version incrementer`

**Comment by adamdubiel** [comment]
Thanks for providing the test, i'm going to have a look at it.

**Comment by adamdubiel** [comment]
I copied the test and run it on `master` and it failed because `VersionPropertiesBuilder.incrementMinor()` method does not exist. After implementing it, test passes. In forked code, i see no implementation of `incrementMinor()` ([file](https://github.com/piotrchowaniec/axion-release-plugin/blob/master/src/test/groovy/pl/allegro/tech/build/axion/release/domain/properties/VersionPropertiesBuilder.groovy)).

You might be observing an issue, but i don't think this tests replicates it. Can you either provide an e2e test (i.e. in `SimpleIntegrationTest`) or describe the issue using command line, steps to replicate etc?

**Comment by piotrchowaniec** [comment]
Test and implementation is on the `respectVersionIncrementer` branch. [file](https://github.com/piotrchowaniec/axion-release-plugin/blob/respectVersionIncrementer/src/test/groovy/pl/allegro/tech/build/axion/release/domain/properties/VersionPropertiesBuilder.groovy). 

In the meantime I've found an error in my configuration (`project.version = scmVersion.version` before `scmVersion` in the build.gradle). So after fixing my configuration I cannot provide any real example of my issue, but still don't know why my test is not working. 

My case was: when I was configuring the plugin to increase minor part of the version calling `gradle currentVersion` returned version with patch number increased. But in the same time doing `gradle release` proper version was created (with minor part increased). 

I'm closing this issue as it was caused by wrong configuration.
Anyway thanks for help.
