### ISSUE TITLE
Increment snapshot version 

### ISSUE THREAD

**Issue by KishorGaneshrao** [allegro/axion-release-plugin#258]
Hi,

Thank you for this wonderful plugin, we are utilising this for our release versioning.

But i was just wondering, with this plugin is there a way to increment the snapshot versions as well? Apart from the first increment from last release tag.
If there were to be multiple commits without tag then the task of currentVersion still provides the same sanpshot version as before. As it always checks the closest commit tag and increments the version.
In our team we do run into cases where we want to track/provide a snapshot version to other teams.

Lets say for e.g
- if the last release version is 1.3.0
- and we have a snapshot version of 1.3.1-SNAPSHOT, and we push that our snapshot library.
- now after few more commits when the next time our CI job tries to push a snapshot artifact to the library it always gets the same version of snapshot as above.
- How do we consider auto increment of these snapshot versions? is there a feature/fecility that we can tap into with this plugin?
-- the only other option that i have come across of is to append a build number for these snapshot versions to be unique.

Appreciate your help on this.

Thank you,
Kishor Ganeshrao

**Comment by adamdubiel** [comment]
Hi :) Thanks for the kind words.

I never thought about adding snapshot increments. The reason is - the version itself did not change. So if version was incremented with each commit, what would be the release version?

```
commitA - 1.3.0
commitB - 1.3.1-SNAPSHOT
commitC - 1.3.2-SNAPSHOT
--- release ---
commitD - 1.3.2? 1.3.3?
```

If you want to have distinct versions for each snapshot, you can utilize version decoration and add short commit revision (mind, this code will also decorate releases!):

```
scmVersion {
    versionCreator { v, p -> "$v-$p.shortRevision" }
}
```

If you want only SNAPSHOT versions deocrated, i would have to think a bit more and probably add some code to `ScmPosition` :)

**Comment by KishorGaneshrao** [comment]
Thank you for the quick response @adamdubiel 

It never really crossed my mind, though I was already using the version Creator with branch. :)

shortRevision works fine for our requirement. :+1:

**Comment by KishorGaneshrao** [comment]
Thanks @adamdubiel , closing this thread
