### ISSUE TITLE
IAM Instance Roles not honored when running release command

### ISSUE THREAD

**Issue by gaglanihetal** [allegro/axion-release-plugin#299]
We have a Jenkins worker on an EC2 instance working with IAM role with all necessary permissions to pull/push using git to codecommit. When we execute straight up git pull/push commands from the instance via jenkins, it works perfectly fine, but when using the plugin via ./gradlew release (which uses jgit), it fails with the below error.

Task :release FAILED
Creating tag: 1.1.36
Pushing all to remote: origin
Exception occurred during push: org.eclipse.jgit.api.errors.TransportException: https://**************/v1/repos/custom-repo: Authentication is required but no CredentialsProvider has been registered

FAILURE: Build failed with an exception.

PS: We were able to get it to work with the following command but this is not the model we want to follow and would rather have jgit use the credentials helper that is configured on AWS instances to apply instance profile just the way git works.

./gradlew --no-daemon clean release -Prelease.customUsername=**** -Prelease.customPassword=****

Thanks for all your work on the plugin! :)

Cheers,
Hetal

**Comment by adamdubiel** [comment]
I did a quick research and:

* this is not `axion-release` problem per se, but rather jgit
* I currently see no workaround for `jgit`, but maybe a more through search would reveal some results?

From the looks of it (I never used code commit) there is a special git extension provided by AWS to sort those things out. I have no idea if it would be possible to use it with `jgit`. However I would greatly appreciate info if you find a way to fix it :)

**Comment by hgaglani** [comment]
Plugin uses JGit internally to issue git command which only works with
Simple username/password git credentials by design as its a simple Java
wrapper around Git. For sophisticated use cases i.e. extracting credentials
from instance profiles, the jgit suggests extending as per needs.

https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/CredentialsProvider.java


Axion release plugin seems to have an implementation for this but it's to
only support username/password credential type:
https://github.com/allegro/axion-release-plugin/tree/master/src/main/groovy/pl/allegro/tech/build/axion/release/infrastructure/git


Spring cloud which also uses jgit internally seems to have extended the
CredentialProvider to work with Jgit:
https://github.com/dlaidlaw/spring-cloud-config/commit/b6ef2276277222c9a9aa3e72f136a066d1b7a02d


I believe a similar solution would be needed to be added to the plug-in
codebase and would require adding aws sdk as a dependency.

Let me know if this is a possibility else we'd look into creating something
custom inhouse.

Thanks again for the quick response.

Cheers,
Hetal Gaglani

**Comment by adamdubiel** [comment]
Oh, great, thanks for finding out that Spring actually did it already.

It is possible that we incorporated this into `axion-release` (borrow code with all license etc etc from Spring) and require AWS SDK as an optional dependency. Would you like to create a PR?

**Comment by hgaglani** [comment]
Awesome that sounds great!! I can create a PR with the same level of
details as I put into this ticket.

Thanks so much for the support.
