### ISSUE TITLE
Release tag ignoring versionCreator

### ISSUE THREAD

**Issue by greenjoe** [allegro/axion-release-plugin#301]
Hello! I would like to release versions from branch that contain the branch name, but for some reason tags created by release task do not have the decoration.  

```
➜  gradle-test git:(mybranch) ✗ ./gradlew currentVersion                                   

> Task :currentVersion 

Project version: 0.1.0-mybranch-SNAPSHOT


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
➜  gradle-test git:(mybranch) ✗ ./gradlew createRelease -Prelease.dryRun  -Prelease.disableChecks

> Task :verifyRelease 
Skipping uncommitted changes check
Skipping ahead of remote check
Skipping snapshot dependencies check

> Task :createRelease 
Creating tag: v-0.1.0
DRY-RUN: creating tag with name: v-0.1.0


BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
```

My configuration is

```
  scmVersion {
        tag {
            prefix = 'v'
        }
        versionCreator 'versionWithBranch'
    }
version = scmVersion
```

I would like the tag to contain `mybranch` too. Is there a way to make it work?

**Comment by adamdubiel** [comment]
This is by design. Branch name is added in "decoration" phase, meaning it is never persisted. Otherwise after you merge branch back to master, what would be the version?

```
release-1.0.0
release-1.0.1-my-branch
```

Is `release-1.0.1-my-branch` more important than `release-1.0.0`? Or `release-1.0.0`, because it was created from master, not branch?

Version numbers / tags are "global", they exist outside the scope of branches.

**Comment by greenjoe** [comment]
Thank you, that makes sense
