### ISSUE TITLE
SnapshotDependenciesChecker fails for multi module project

### ISSUE THREAD

**Issue by mazdack** [allegro/axion-release-plugin#330]
For example you have 2 modules: api and server.
Server uses api module like this `implementation(project(":api"))`
Then the snapshot check fails:
`> The project uses snapshot versions - can't release. Snapshots found`

I think there should be possibility to ignore some dependencies.

**Comment by Kindrat** [comment]
Same here. All project() dependencies are breaking release.

**Comment by dlesniakdev** [comment]
@Kindrat is your change actually releasing `SNAPSHOT` dependencies? That would be cool, stuck on this one. 

I have similar issue but instead of ignoring `SNAPSHOT`s I'd rather like to have possibility to release them to full version. It's because I'd like to run `./gradlew release` on whole multiproject instead of on concrete modules in proper order.

**Comment by Kindrat** [comment]
@dlesniakdev yeah, that was for snapshot release. All external deps are releases, while internal modules are snapshots.

**Comment by k3mist** [comment]
We have an internal plugin that we include Axion with and also encountered this issue when updating;

Downgrading Axion to `1.10.3` resolves it for us

`> 1.10.3`
```
→% gradle currentversion

> Task :currentVersion
Current Version:
Gradle Detected: 1.1.4
Axion Detected: 1.1.4
Internal Detected: 1.1.4

> Task :jar-sub:currentVersion
Current Version:
Gradle Detected: 1.1.5-SNAPSHOT
Axion Detected: 1.1.5-SNAPSHOT
Internal Detected: 1.1.5-SNAPSHOT
```

`<= 1.10.3`
```
→% gradle currentversion

> Task :currentVersion
Current Version:
Gradle Detected: 1.1.4
Axion Detected: 1.1.4
Internal Detected: 1.1.4

> Task :jar-sub:currentVersion
Current Version:
Gradle Detected: 1.1.4
Axion Detected: 1.1.4
Internal Detected: 1.1.4
```

It appears its most likely related to changes that occurred with; https://github.com/allegro/axion-release-plugin/commit/7202376bba5549a2ac75976f2bf4730638c02f25

But I'm not sure how we opt-out of this behavior and should have probably been opt-in instead of changing the existing default behavior

**Comment by radusuma** [comment]
Hello,
 
I am facing the same issue SnapshotDependenciesChecker fails for multi module project.
did anyone able to resolve it ?

**Comment by gabrieljones** [comment]
I just ran into this, but only due to upgrading to gradle 7.6. On gradle 7.5.1 I did not have this problem.

**Comment by gabrieljones** [comment]
Turns out my problems stemmed from having the plugin on each submodule when I really wanted it only on the root project.

**Comment by bgalek** [comment]
merged and released!
