### ISSUE TITLE
Release and publish with one command

### ISSUE THREAD

**Issue by houbie** [allegro/axion-release-plugin#62]
When building a release I typically want everything to be done with one command, including the uploading to a repository and preparing a new snapshot version.
The docs state that you have to execute the publish in a separate command because otherwise the version would not be correct, but there is an easy workaround for that: fork a new gradle build for the upload.

This is how I modified my gradle build file:

```java
task updateReadme << {
    // I just found out that this is already supported :)
}

task commitReadme << {
    // I just found out that this is already supported :)
}

task forkedUpload(type: GradleBuild) {
    buildFile = project.buildFile
    // update the readme before uploading, because the distributions contain the readme
    tasks = ['updateReadme', 'uploadArchives', 'commitReadme']
}

// when releasing, I always want to do a clean and run all tests
build.mustRunAfter(clean)
release.dependsOn(clean, build)

release << {
    tasks.forkedUpload.execute()
}
```

I think that it makes sense to provide this functionality out of the box in the release plugin:
```java
scmVersion {
    preReleaseTasks= [clean, build] //or predefined hooks 'clean' and 'build' that are added by default? 
    uploadArchives= true //default
}
```

**Comment by houbie** [comment]
After switching to 1.2.1, I reworked it to the following:

```java
// I would expect this to be pre-defined by the release plugin
task forkedUpload(type: GradleBuild) {
    buildFile = project.buildFile
    tasks = ['uploadArchives']
}

scmVersion {
    hooks {
        pre 'fileUpdate', [file       : 'README.md',
                           pattern    : { previousVersion, scmPosition -> previousVersion },
                           replacement: { newVersion, scmPosition -> newVersion }]
        //following should preferably be pre-defined by default, optionally disabled with 'uploadArchives=false'
        post { context -> tasks.forkedUpload.execute() }

        //the commit has to come after the upload, otherwise the forked upload will already have the new snapshot version
        //the commit pattern added by the fileUpdate is not available anymore for the post hook, we have to add it manually
        // ideally this would be done automatically when 'createReleaseCommit=true'
        post { context -> context.commit(['README.md'], "Release version: $context.currentVersion") }
    }
}

//following would also be a reasonable default behavior
build.mustRunAfter(clean)
release.dependsOn(clean, build)
```

**Comment by adamdubiel** [comment]
#### Defaults

What seems like reasonable for you, might not be so in other cases :)

Gradle is great because it's so flexible. I would not want to break this by adding default dependencies on tasks, which i think should be build or case-specific. Running `clean build` before release might be perfectly reasonable (or even required) in your environment, but in our CI pipeline this would just cause unnecessary overhead. I want `release` to be task that plays well with the others.

Your use of hooks is also very different from mine (and people that created that issue). TBH i even considered removing `post` hook, as i could not see any case for using it. But this is great - it means axion-release is flexible enough to meet different requirements.

So, while the setup you presented might seem like the best option for you, it might not be so for other users of axion-release and that's why i don't want to include it as default.

#### Publishing

Publishing and release is another issue. This again, i'm afraid, depends on usage. We are all used to Maven release, which did everything in one (very complicated!) run. But release and publish are not the same and there are a lot of configurations and customizations in this process - starting from choice of plugin (`uploadArchives/maven` or `publish/maven-publish` to Bintray publishing plugin and probably more), through additional tasks (like singing). Just as with *Defaults* paragraph, my conclusion is - let's keep axion-release good citizen of Gradle world that does not try to mess with peoples build too much by default.

**Comment by adamdubiel** [comment]
I will close this issue, feel free to comment on my remarks if you have some thoughts though.
