### ISSUE TITLE
Issue on creating new tag in gradle, local machine and github action

### ISSUE THREAD

**Issue by yuvaraj119** [allegro/axion-release-plugin#677]
I create a tag manually using github release tag and once the tag is created i see in github action the cV becomes snapshot.
Using latest [v1.15.5](https://github.com/allegro/axion-release-plugin/releases/tag/v1.15.5)
gradle-7.5

```
./gradlew cV
Project version: 1.0.3-SNAPSHOT
./gradlew release
Creating tag: v1.0.3
$ git tag
v0.0.1
v1.0.0
v1.0.1
v1.0.2
v1.0.3

./gradlew cV
Project version: 1.0.4-SNAPSHOT

Here is my version gradle 
apply plugin: 'pl.allegro.tech.build.axion-release'

scmVersion {
    monorepo {
        projectDirs = project.subprojects.collect({ p -> p.name })
    }
    checks {
        uncommittedChanges.set(false)
        aheadOfRemote.set(false)
        snapshotDependencies.set(false)
    }
    repository {
        pushTagsOnly = true
        remote = "pushback"
    }
}
```

Issue here is after merging multiple feature, develop branches into main and then when i generate release tag this issue occurs.
If i do one commit directly to main then it works good and generates the given tag version.

**Comment by bgalek** [comment]
hi!
did you remembered to add fetch-depth: 0 to your `checkout` github action?

**Comment by scprek** [comment]
I have this issue when I do the release in the action, which creates/pushes the correct tags, but then publish adds snapshot to the artifacts

**Comment by bgalek** [comment]
@scprek do you create your release tasks using axion-gradle-plugin?

**Comment by scprek** [comment]
So I believe the issue was me trying to be clever setting everything in subprojects. I went through a ton of variations of setting up submodules in the most unified way. The only way I could reverse engineer what to do was via `tasks.withType<BaseAxionTask>`.

Maybe we should add an example of how to best do this when not applying the plugin at the root level. I wanted to avoid having any root versioning/artifacts and simply use the repo has a mono repo for a collection of modules. No BOM or anything. Does this seem reasonable?

Top level `build.gradle.kts`

```kotlin
plugins {
   id("pl.allegro.tech.build.axion-release") version "1.16.1" apply false
}

subprojects {
   plugins.apply("pl.allegro.tech.build.axion-release")


  tasks.withType<BaseAxionTask> {
      version = versionConfig.version // <-- This only works with release NOT cV and publish whoops!
  
      versionConfig.tag {
          prefix.set(project.name)
          versionSeparator.set("_")
      }
  
      versionConfig.branchVersionIncrementer.putAll(
          mapOf<String, Any>(
              "micronaut.*" to VersionProperties.Incrementer { c: VersionIncrementerContext -> c.currentVersion.incrementPatchVersion() }
          )
      )
  }
}
```

In `module/build.gradle.kts`
```
version = scmVersion.version
```
